project:
  type: website
  resources:
    - images/**

website:
  title: "Jorge Juvenal Campos Ferreira"
  description: "Ciencia de datos · Periodismo de datos · Docencia"

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Inicio
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/JuveCampos
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/JuvenalCamposF
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/jorge-juvenal-campos-ferreira-5532b7160/
        aria-label: LinkedIn
      - icon: instagram
        href: https://www.instagram.com/juvenalcampos.dataviz/
        aria-label: Instagram

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - includes/after-body.html
    toc: true
    code-fold: false
    highlight-style: github
    lang: es

execute:
  freeze: auto
